# ===================================================================
# Configuração de Banco de Dados PostgreSQL no Render (Produção)
# ===================================================================

# A URL deve apontar APENAS para o host, porta e banco de dados (sem usuário e senha embarcados)
spring.datasource.url=${JDBC_DATABASE_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-dasmodjbc2fs73fuqn10-a.virginia-postgres.render.com:5432/dbdevshowcase_1bji}}
spring.datasource.username=${JDBC_DATABASE_USERNAME:${SPRING_DATASOURCE_USERNAME:root}}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:${SPRING_DATASOURCE_PASSWORD:mEGhBEB28QozutxrrSSUnQxWnTxPQnd0}}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Mapeamento do Swagger UI e OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.operationsSorter=method
springdoc.show-actuator=true

# Mapeamento e Liberacao do Swagger
springdoc.packages-to-scan=br.com.sawa.devshowcase_api.controller